# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0.xci
# IP: The module: 'zed_design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0.xci
# IP: The module: 'zed_design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/cpre488/Labs/MP-0/hardware_system_mp0/hardware_system_mp0.srcs/sources_1/bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
