# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zed_design_1/zed_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1 || ORIG_REF_NAME==zed_design_1} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_processing_system7_0_0/zed_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_processing_system7_0_0 || ORIG_REF_NAME==zed_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_axi_gpio_0_0/zed_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zed_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_axi_gpio_1_0/zed_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_axi_gpio_1_0 || ORIG_REF_NAME==zed_design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_axi_gpio_1_1/zed_design_1_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_axi_gpio_1_1 || ORIG_REF_NAME==zed_design_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_xbar_0/zed_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_xbar_0 || ORIG_REF_NAME==zed_design_1_xbar_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_ps7_0_axi_periph_0/zed_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zed_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_rst_ps7_0_100M_0/zed_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==zed_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zed_design_1/ip/zed_design_1_auto_pc_0/zed_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_design_1_auto_pc_0 || ORIG_REF_NAME==zed_design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/zed_design_1/zed_design_1_ooc.xdc
